[project]
name = "flex-templates"
version = "0.1"
dependencies = ["flet>=0.20.0","pandas>=2.2.1"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project.scripts]
flex-start = "src.main:main"